{
 "title": "USE Metrics",
 "tags": [ "use" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "service",
    "label": "Service",
    "query": {
     "query": "label_values({job!=\"node-exporter\", job!=\"loki\"},job)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Utilization",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=~\"$service\"}[5m]) * 100",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (job, instance) ((process_resident_memory_bytes{job=~\"$service\"} * 100) / on (instance) group_left node_memory_MemTotal_bytes)\n",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "mps" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "rate({service_name=~\"$service\"} [$__auto])",
     "legendFormat": "{{service_name}}: {{detected_level}}"
    }
   ]
  },
  { "title": "Saturation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "CPU Load Average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=~\"$service\"}[5m])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=~\"$service\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  { "title": "Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "HTTP 5xx Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "rate(http_requests_total{job=~\"$service\", status=~\"5..\"}[5m])",
     "legendFormat": "{{job}} {{method}} {{path}}"
    }
   ]
  },
  {
   "title": "Error Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=~\"$service\"} |~ `(?i)error` | json"
    }
   ]
  }
 ]
}