services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always

  prometheus:
    image: prom/prometheus:v3
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    restart: always

  grafana:
    image: grafana/grafana:13.0
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    volumes:
      - ./datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
    depends_on:
      - prometheus

  k6:
    image: grafana/k6:v2
    volumes:
      - ./script.js:/script.js
    command: run /script.js
    depends_on:
      - app
