apiVersion: 1

datasources:
  - name: VictoriaMetrics
    type: victoriametrics-metrics-datasource
    access: proxy
    url: http://victoria:8428
    isDefault: true
    jsonData:
      httpMethod: GET