{
 "title": "Product catalog",
 "time": { "from": "now-10m", "to": "now" },
 "panels": [
  { "title": "Service overall", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Distribution of statuses over past 5 minutes",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(status) (rate(http_requests_total{path!=\"/metrics\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency distribution over endpoints",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le, path, status) (rate(http_requests_latency_seconds_bucket{path!=\"/metrics\"}[$__rate_interval])))",
     "legendFormat": "{{status}}: {{path}} 99p"
    }
   ]
  },
  {
   "title": "RPS per status/endpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(path, status) (rate(http_requests_total{path!=\"/metrics\"}[$__rate_interval]))",
     "legendFormat": "{{status}}: {{path}}"
    }
   ]
  },
  { "title": "Per nodes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Average memory usage ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by(k8s_node) (go_memstats_heap_sys_bytes)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency distribution over nodes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.999, sum by(le, k8s_node) (rate(http_requests_latency_seconds_bucket{path!=\"/metrics\"}[$__rate_interval])))",
     "legendFormat": "{{k8s_node}} 999p"
    }
   ]
  },
  {
   "title": "RPS per k8s node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(k8s_node) (rate(http_requests_total{path!=\"/metrics\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}