{
 "title": "Queries",
 "time": { "from": "now-2h", "to": "now+10m" },
 "panels": [
  {
   "title": "95-й перцентиль latency HTTP запросов по инстансам",
   "type": "timeseries",
   "description": "Например: tail latency API растёт на одном из backend-инстансов → проблема в GC, блокировках или сетевой деградации.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[5m])) by (le, instance))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Фильтрация регулярных циклов (пики активности пользователей в зависимости от времени суток)",
   "type": "timeseries",
   "description": "Например: скользящее среднее помогает выделить реальный тренд, а не сезонные колебания",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "avg_over_time(sinusoidal_metric[1m])",
     "legendFormat": "avg_over_time {{instance}}"
    }
   ]
  },
  {
   "title": "Количество ошибок в секунду",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(increasing_counter_metric[1m])",
     "legendFormat": "rate {{instance}}"
    }
   ]
  },
  {
   "title": "Пропуск скрейпов",
   "type": "timeseries",
   "description": "например, instance отвалился, из-за сетевых проблем, counter прекращает расти.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "absent(missing_scrape_counter_metric)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Standart deviation (CPU usage)",
   "type": "timeseries",
   "description": "Поиск аномальных спайков нагрузки, ошибок или задержек, например:\n- резкий всплеск CPU,\n- burst трафика,\n- короткие пики latency, приводящие к деградации.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "stddev_over_time(spiky_metric[4s])",
     "legendFormat": "stddev {{instance}}"
    },
    { "expr": "spiky_metric", "legendFormat": "original metric {{instance}}" }
   ]
  },
  {
   "title": "Standart deviation (memory usage)",
   "type": "timeseries",
   "description": "Поиск аномальных спайков нагрузки, ошибок или задержек, например:\n- резкий всплеск CPU,\n- burst трафика,\n- короткие пики latency, приводящие к деградации.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "stddev_over_time(step_changes_metric[4s])",
     "legendFormat": "stddev {{instance}}"
    },
    { "expr": "step_changes_metric", "legendFormat": "original metric {{instance}}" }
   ]
  },
  {
   "title": "\"Предсказание\" роста метрики",
   "type": "timeseries",
   "description": "Например:\n* очередь уходит в бесконечный рост\n* память процесса растёт\n* потребление диска растет",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "predict_linear(increasing_counter_metric[1m], 10m)",
     "legendFormat": "predict {{instance}}"
    },
    { "expr": "increasing_counter_metric", "legendFormat": "original {{instance}}" }
   ]
  },
  {
   "title": "Обнаружение reset метрик",
   "type": "timeseries",
   "description": "* очередь задач, которую периодически очищают\n* temp файлы/кэши, которые периодически чистятся",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "(deriv(periodic_reset_metric[3m]) > 1) * avg_over_time(periodic_reset_metric[3m])",
     "legendFormat": "reset {{instance}}"
    },
    { "expr": "periodic_reset_metric", "legendFormat": "original {{instance}}" }
   ]
  },
  {
   "title": "Сглаживание шума",
   "type": "timeseries",
   "description": "Например, спайки latency",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "median_over_time(noisy_baseline_metric[1m])",
     "legendFormat": "smoothed {{instance}}"
    },
    { "expr": "noisy_baseline_metric", "legendFormat": "original {{instance}}" }
   ]
  },
  {
   "title": "Экспоненциальный рост",
   "type": "timeseries",
   "description": "Например, быстрый рост memory usage",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "deriv(exponential_growth_metric[1m])",
     "legendFormat": "deriv {{instance}}"
    },
    { "expr": "exponential_growth_metric", "legendFormat": "original {{instance}}" }
   ]
  },
  {
   "title": "Медленный спад",
   "type": "timeseries",
   "description": "Например, нагрузка на сервис падает. Или кол-во клиентов ниже ночью",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "delta(gradual_decay_metric[1m])",
     "legendFormat": "delta {{instance}}"
    },
    { "expr": "gradual_decay_metric", "legendFormat": "original {{instance}}" }
   ]
  },
  {
   "title": "Резкие изменения метрики",
   "type": "timeseries",
   "description": "Например, сработал автоскейлинг.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "changes(step_changes_metric[1m])",
     "legendFormat": "changes {{instance}}"
    },
    { "expr": "step_changes_metric", "legendFormat": "original {{instance}}" }
   ]
  }
 ]
}