{
 "title": "Решение ДЗ",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Резкие всплески",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "spike_metric", "legendFormat": "__auto" },
    {
     "expr": "spike_metric > avg_over_time(spike_metric[1m]) + 0.3 * stddev_over_time(spike_metric[1m])",
     "legendFormat": "Alert"
    }
   ]
  },
  {
   "title": "Изменение сезонности",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "sinusoidal_metric", "legendFormat": "__auto" },
    {
     "expr": "abs(stddev_over_time(sinusoidal_metric[1m]) - stddev_over_time(sinusoidal_metric[1m] offset 5m)) > 1",
     "legendFormat": "Alert"
    }
   ]
  },
  {
   "title": "Замедление скорости роста",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "linear_metric", "legendFormat": "__auto" },
    {
     "expr": "deriv(linear_metric[1m]) < 0.3 * deriv(linear_metric[1m] offset 5m)",
     "legendFormat": "Alert"
    }
   ]
  }
 ]
}