apiVersion: 1
groups:
  - orgId: 1
    name: every-1m
    folder: taxi-system
    interval: 1m
    rules:
      - uid: degu78mvabn5sb
        title: Not enough drivers online (<110)
        condition: A
        data:
          - refId: A
            relativeTimeRange:
              from: 600
              to: 0
            datasourceUid: victoriametrics
            model:
              editorMode: code
              expr: count by (job) (driver_location_updates_total{job="driver-location-service"}[10m])
              instant: true
              intervalMs: 1000
              legendFormat: __auto
              maxDataPoints: 43200
              range: false
              refId: A
          - refId: B
            datasourceUid: __expr__
            model:
              conditions:
                - evaluator:
                    params:
                      - 110
                      - 0
                    type: lt
                  operator:
                    type: and
                  query:
                    params: []
                  reducer:
                    params: []
                    type: avg
                  type: query
              datasource:
                name: Expression
                type: __expr__
                uid: __expr__
              expression: A
              intervalMs: 1000
              maxDataPoints: 43200
              refId: B
              type: threshold
        noDataState: NoData
        execErrState: Error
        for: 1m
        labels:
          kind: drivers
        isPaused: false
        notification_settings:
          receiver: grafana-default-email
