global:
  scrape_interval: 2s

scrape_configs:
  - job_name: 'order-service'
    static_configs:
      - targets: ['app:8080']
        labels:
          service_name: app

rule_files:
  - rules/sli-recording-rules.yaml
  - rules/error-budget-rules.yaml
  - rules/burn-rate-alerts.yaml
