apiVersion: 1

datasources:
  - name: VictoriaMetrics
    uid: victoriametrics
    type: prometheus
    access: proxy
    url: http://victoriametrics:8428
    isDefault: true

  - name: Pyroscope
    uid: pyroscope
    type: grafana-pyroscope-datasource
    url: http://pyroscope:4040
    editable: false

  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090

  - name: Graphite
    uid: graphite
    type: graphite
    access: proxy
    url: http://graphite:80

  - name: Tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    uid: tempo
    jsonData:
      httpMethod: GET
      serviceMap:
        datasourceUid: 'victoriametrics'
      search:
        hide: false
      nodeGraph:
        enabled: true
      lokiSearch:
        datasourceUid: 'loki'
      tracesToProfiles:
        datasourceUid: 'pyroscope'
        profileTypeId: 'process_cpu:cpu:nanoseconds:cpu:nanoseconds'

  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    uid: loki
    jsonData:
      maxLines: 1000
      derivedFields:
        - datasourceUid: tempo
          matcherRegex: "\"traceID\":\"(\\w+)\""
          name: TraceID
          url: "$${__value.raw}"

  - name: Infinity
    type: yesoreyeram-infinity-datasource
    uid: infinity
    jsonData:
      type: rest
      dataFormat: json