{
 "title": "Lesson 4 sample solution",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "SERVICE",
    "label": "Service",
    "query": {
     "query": "label_values(http_requests_total,job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "$SERVICE: RPS per endpoint/status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "repeat": "SERVICE",
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(http_requests_total{job=\"$SERVICE\"}[5m])",
     "legendFormat": "{{path}} {{status}}"
    }
   ]
  },
  {
   "title": "$SERVICE: Latency per endpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "repeat": "SERVICE",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{job=\"$SERVICE\"}[5m])) by (le, path))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$SERVICE: Errors",
   "type": "status-history",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 16 },
   "repeat": "SERVICE",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(\n  sum by (path) (rate(http_requests_total{status=~\"2..\", job=\"$SERVICE\"}[5m]))\n  /\n  (sum by (path) (rate(http_requests_total{job=\"$SERVICE\"}[5m])))\n) * 100 or vector(-1)",
     "legendFormat": "{{path}}"
    }
   ]
  }
 ]
}