{
 "title": "Service Overview",
 "tags": [ "overview" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "service", "label": "Service", "query": { "query": "label_values(job)" } },
   {
    "name": "path",
    "label": "Path",
    "query": {
     "query": "label_values(http_requests_total{job=~\"$service\"},path)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Service Health Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Request Rate",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(job) (rate(http_requests_total{job=~\"$service\", path=~\"$path\"}[5m]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Average Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_sum{job=~\"$service\", path=~\"$path\"}[5m]) / rate(http_request_duration_seconds_count{job=~\"$service\"}[5m])",
     "legendFormat": "{{job}} {{method}} {{path}}"
    }
   ]
  },
  {
   "title": "95th Percentile Latency (histogram) (exemplars)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(http_request_duration_seconds_bucket{job=~\"$service\", path=~\"$path\"}[5m]))",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  },
  {
   "title": "95th Percentile Latency amount of queries (summary)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "http_request_duration_seconds_summary{job=~\"$service\", quantile=\"0.95\", path!~\"$path\"}",
     "legendFormat": "{{method}} {{path}} {{ quantile }}"
    },
    {
     "expr": "http_request_duration_seconds_summary{job=~\"$service\", quantile=\"0.99\", path!~\"$path\"}",
     "legendFormat": "{{method}} {{path}} {{ quantile }}"
    },
    {
     "expr": "http_request_duration_seconds_summary{job=~\"$service\", quantile=\"0.9\", path=~\"$path\"}",
     "legendFormat": "{{job}} {{method}} {{path}} {{ quantile }}"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum by(job, method, path) (rate(http_requests_total{job=~\"$service\", status!~\"2..\", path=~\"$path\"}[5m])) * 100) / sum by(job, method, path) (rate(http_requests_total{job=~\"$service\", path=~\"$path\"}[5m]))",
     "legendFormat": "{{ job }} {{method}} {{path}} "
    }
   ]
  },
  { "title": "Resource Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=~\"$service\"}[5m]) * 100",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "targets": [
    {
     "downsampler": "max",
     "expression": "A",
     "settings": { "mode": "dropNN" },
     "type": "resample",
     "upsampler": "backfilling",
     "window": "5m"
    }
   ]
  }
 ]
}