groups:
  - name: AlwaysFiringAlerts
    labels:
      team: example
    rules:
      - alert: AlwaysFiringWarning
        expr: vector(1)
        for: 0m  # Fire immediately
        labels:
          severity: warning
        annotations:
          summary: "Always Firing Warning Alert"
          description: "This alert is designed to always fire with warning severity."

      - alert: AlwaysFiringCritical
        expr: vector(1)
        for: 0m  # Fire immediately
        labels:
          severity: critical
        annotations:
          summary: "Always Firing Critical Alert"
          description: "This alert is designed to always fire with critical severity."

  - name: TrackAnalyzerService
    labels:
      job: track-analyzer-service
    rules:
      - alert: Http5XXErrorRateTooHigh
        expr: rate(http_requests_total{job="track-analyzer-service", status=~"5.."}[5m]) > 10
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Http 5xx errors"