{
 "title": "SLO Dashboard",
 "description": "Tracks service's SLO and error budget consumption.",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "job",
    "query": {
     "query": "label_values(http_requests_total,job)"
    }
   },
   {
    "name": "service_requests_error_count",
    "query": "http_requests_total{job=\"$job\", status=~\"5..\"}"
   },
   {
    "name": "service_requests_total_count",
    "query": "http_requests_total{job=\"$job\"}"
   },
   {
    "name": "alerts_filter_criteria",
    "query": "job=\"$job\""
   },
   { "name": "service_slo_target", "query": "95" },
   { "name": "error_budget", "query": "0.05" }
  ]
 },
 "panels": [
  { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 } },
  {
   "title": "Current SLO",
   "type": "stat",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - sum(rate($service_requests_error_count[28d])) by (job) / sum(rate($service_requests_total_count[28d])) by (job)"
    }
   ]
  },
  {
   "title": "Error Budget Left",
   "type": "stat",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "28 * 24 * ($error_budget - sum(rate($service_requests_error_count[28d])) by (job) / sum(rate($service_requests_total_count[28d])) by (job))"
    }
   ]
  },
  {
   "title": "28 Day Window SLO $job",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "$service_slo_target", "legendFormat": "target" },
    {
     "expr": "(1 - sum(rate($service_requests_error_count[28d])) by (job) / sum(rate($service_requests_total_count[28d])) by (job)) * 100",
     "legendFormat": "real"
    }
   ]
  },
  {
   "title": "Probe Error Ratio $job",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate($service_requests_error_count[1m])) by (job) / sum(rate($service_requests_total_count[1m])) by (job)",
     "legendFormat": "error ratio"
    }
   ]
  },
  {
   "title": "Requests Rate $job",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate($service_requests_total_count[1m])) by (job)",
     "legendFormat": "total requests rate"
    },
    {
     "expr": "sum(rate($service_requests_error_count[1m])) by (job)",
     "legendFormat": "error responses rate"
    }
   ]
  }
 ]
}