{
 "title": "Golden Signals Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "service",
    "label": "Service",
    "query": {
     "query": "label_values(http_requests_total,job)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Golden Signals: $service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "service" },
  {
   "title": "Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(status) (rate(http_requests_total{job=~\"$service\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(job) (histogram_quantile(0.99, rate(http_request_duration_seconds_bucket{job=~\"$service\"}[5m])))",
     "legendFormat": "{{job}} 99%"
    },
    {
     "expr": "sum by(job) (histogram_quantile(0.9, rate(http_request_duration_seconds_bucket{job=~\"$service\"}[5m])))",
     "legendFormat": "{{job}} 90%"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum(rate(http_requests_total{job=~\"$service\", status!~\"2..\"}[5m])) * 100) / sum(rate(http_requests_total{job=~\"$service\"}[5m]))",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  },
  {
   "title": "Saturation (goroutines) (log2)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum by(job) (rate(go_goroutines{job=~\"$service\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Budget (10 min)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - (sum(rate(http_requests_total{job=~\"$service\",status!~\"2..\"}[10m])) / sum(rate(http_requests_total{job=~\"$service\"}[10m])))) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Budget (10 min)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - (sum(rate(http_requests_total{job=~\"$service\",status!~\"2..\"}[1h])) / sum(rate(http_requests_total{job=~\"$service\"}[1h])))) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Budget (10 min)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(1 - (sum(rate(http_requests_total{job=~\"$service\",status!~\"2..\"}[10m])) / sum(rate(http_requests_total{job=~\"$service\"}[10m])))) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Budget (1h)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
   "targets": [
    {
     "expr": "(1 - (sum(rate(http_requests_total{job=~\"$service\",status!~\"2..\"}[1h])) / sum(rate(http_requests_total{job=~\"$service\"}[1h])))) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latencies by endpoints",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "sum by(le, job, path) (rate(http_request_duration_seconds_bucket{job=~\"$service\", le=~\"0.1|0.5|1\"}[1m]))",
     "legendFormat": "{{ path }} < {{ le }} s"
    }
   ]
  },
  {
   "title": "Endpoints health",
   "type": "status-history",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum by (path) (rate(http_requests_total{job=\"$service\", status=~\"2..\"}[1m])) * 60) / (sum by (path) (rate(http_requests_total{job=\"$service\"}[1m])) * 60) * 100",
     "legendFormat": "{{ job }} {{ path }}"
    }
   ]
  }
 ]
}